### ISSUE TITLE
0.1.2 release breaks require() of this dependency from angular-hypermedia package.json

### ISSUE THREAD

**Issue by albert-tarly** [jcassee/mediatype-parser#2]

**Comment by jcassee** [comment]
Hi @besuhoff, can you tell me a bit more about how 0.1.2 broke `require()`?

**Comment by albert-tarly** [comment]
Hi @jcassee, sure.

You have in your package.json in [angular-hypermedia ](https://github.com/jcassee/angular-hypermedia) versions of this and linkheader-parser libraries set to `^0.1`, so yesterday it jumped from 0.1.1 up to 0.1.2, the latest one.

We're using angular-hypermedia under webpack, and we use **ProvidePlugin** to provide values for global variables in that library:

```
  new webpack.ProvidePlugin({
    ...
    mediaTypeParser: 'mediatype-parser',
    linkHeaderParser: 'linkheader-parser',
    UriTemplate: 'uri-templates',
    ...
  })
```

**ProvidePlugin** uses require for the modules and imports those to variables, but when it fails, it will return an empty object. So today we've found out that it returns empty objects for mediaTypeParser and linkHeaderParser.

**Comment by jcassee** [comment]
Okay, thanks. Do you know how to fix this? It has something to do with the `"browser"` property that was added to package.json, but I am not familiar with Webpack.

**Comment by albert-tarly** [comment]
Yeah, I looked into it and I now know. It's because first you only had `main` field in `package.json`, but you now also have `browser` field. So it had been imported priorly as `mediatype-parser-node.js`, which is perfectly suitable for webpack as is defined as a module, but now it changed to a higher priority file `mediatype-parser-browser.js` which is defined as global variable!

**Comment by albert-tarly** [comment]
I think we might want our webpack to look into `main` only though I'm not sure whether it's good or not to have browser package defined as global variable

**Comment by jcassee** [comment]
Okay, so the `browser` field was requested to make it work with Browserify (see #1). I only use Bower at the moment, and I know that `mediatype-parser-browser.js` works in that situation. I had hoped `mediatype-parser-node.js` was good for Browserify, Webpack and other Node-based packagers.

Do you know how I can make everyone happy?

**Comment by albert-tarly** [comment]
I think we should handle it on our end, sorry for bothering. It's worth to know though for Webpack users that they need to change order of field names in `resolve.packageMains` from now on

**Comment by jcassee** [comment]
Okay, thanks for the info. I am closing the ticket.
